Testngparalleltesting
alesiavaronich/SauceDemoProj pull request #1
Opened 2022-08-22 09:35 UTC by alesiavaronich

Расширила проект значительно - помимо обязательных заданий добавила логи, Allure report, javadocs. 
Изменила некоторые тесты и проверки.

2022-08-23 20:01 UTC, khadasevich requested changes

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/drivermanager/threadlocalmanager/FirefoxDriverThreadLocalManager.java
> +                Arrays.asList("disable-popup-blocking"));
Each browser has own options and it requires investigation each time you need something to resolve. In this case:
FirefoxOptions options = new FirefoxOptions();
    options.addPreference("dom.webnotifications.enabled", false);

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/tests/BaseWithDriverFactoryTest.java
> +            type = DriverType.REMOTE;
Yes, since you have remote driver set up implementation

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/tests/CartTests.java
> +        driverManager.getDriver().get(Urls.SAUCEDEMO_LOGIN_URL);
Let's hide opening of the page to service

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/tests/CartTests.java
> +        log.info(String.format("Opening cart"));
String.format("%s", "s") has sense only if you want to insert sum substring into some string in this place it's senseless, here should be something like log.info("Opening cart");

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/tests/CartTests.java
> +        Assert.assertTrue(productsPage.validateTextFromButton());
Seems like only you will know what's wrong with test if assertion fails, let's add assertion message

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/tests/LoginWithBuilderLombokModelTest.java
> -        //to-do: add assertion
Seems like assertion in the end of this test is enough for this test

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/tests/LoginWithBuilderLombokModelTest.java
> +        Assert.assertTrue(getLoginPage().isErrorMessageVisible());
Assertion in the end of this test will be enough

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/tests/LoginWithBuilderLombokModelTest.java
> +        //Need help with assert here
Just add ordinary check for login, this problem user has bad images after login. So, image recognition is possible but isn't in scope of our course

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/tests/LoginWithBuilderLombokModelTest.java
> +        //Need help with assert here
Ordinary check of login. It makes sense to add dataProvider to main test for login and as data send standard_user,
problem_user, performance_glitch_user models to test

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/tests/LoginWithExplicitWaitTest.java
>          driver.getWindowHandles().forEach(tab -> driver.switchTo().window(tab));
Move this code to page

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/tests/LoginWithExplicitWaitTest.java
> -        //wait.until(ExpectedConditions.visibilityOf(linkedInPage.returnLinkedInLogo())); // test fails, doesn't find element HELP!
Move wait to method of page

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/tests/LoginWithExplicitWaitTest.java
> +        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//icon[@data-test-id='nav-logo']")));
Move to page

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/tests/LoginWithExplicitWaitTest.java
> -        //wait.until(ExpectedConditions.visibilityOf(linkedInPage.returnLinkedInLogo())); // test fails, doesn't find element HELP!
wait.until(ExpectedConditions.visibilityOf(linkedInPage.returnLinkedInLogo())) doesn't work because this condition requires already located web element, visibilityOfElementLocated perfoms search of element by locator that's why it doesn't fail

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/tests/LoginWithFluentTest.java
>          Assert.assertTrue(isProductsDisplayed);
Missed assertion message

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/tests/ProductsTests.java
> +        driverManager.getDriver().get(Urls.SAUCEDEMO_LOGIN_URL);
move open of login url to service

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/pages/LoginPage.java
Do not see chain of invocations and loadable component patterns implemented required for HW 11

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/pages/ProductsPage.java
Do not see chain of invocations and loadable component patterns implemented required for HW 11

2022-08-23 20:01 UTC, khadasevich commented on src/test/java/pages/LoginPage.java
>      private By username = By.cssSelector("[data-test='username']");
Do not see chain of invocations and loadable component patterns implemented required for HW 11

2022-09-05 08:48 UTC, alesiavaronich commented on src/test/java/drivermanager/threadlocalmanager/FirefoxDriverThreadLocalManager.java
> +                Arrays.asList("disable-popup-blocking"));
Thank you!

2022-09-05 14:30 UTC, alesiavaronich commented on src/test/java/tests/LoginWithBuilderLombokModelTest.java
> -        //to-do: add assertion
removed excessive asserts

2022-09-11 12:23 UTC, khadasevich approved these changes

2022-09-11 12:23 UTC, merged